### ISSUE TITLE
is it compatible with Suspense?

### ISSUE THREAD

**Issue by itaditya** [f/react-wait#2]
Hi, the React team has launced Suspense for data loading and is about to release it for concurrent updates. Is this library using that or is this is a custom solution?

**Comment by f** [comment]
Suspense is not about data fetching right now, it's about code splitting. This is an alternative for vue-wait https://twitter.com/dan_abramov/status/1055294178001862658?s=19

**Comment by itaditya** [comment]
Oh sorry, I got confused, you're right it's not currently for data loading but soon Suspense will be the de-facto solution for most asynchronous behaviour in React. Basically we will be able to provide a fallback component till the actual component loads. So `use-wait` should take that into account.

**Comment by f** [comment]
Yeah, Suspense would be better approach when it's released since it's built-in.

**Comment by f** [comment]
I've added a note: https://github.com/f/use-wait#why-not-reactsuspense

**Comment by itaditya** [comment]
Thanks! that's a great step. Minor suggestion it should be

> React has its own Suspense feature to manage all the async works. ~It's~ For now it only supports code-splitting (not data-fetching).
